### ISSUE TITLE
all unit test cases are not being executed via tox

### ISSUE THREAD

**Issue by svt-kmcdaniel** [HewlettPackard/simplivity-python-sdk#1]
There appears to be a total of 106 unique unit test cases within the ./tests/unit directory structure

`python -m unittest discover` executes the 34 test cases directory under ./tests/unit, but skips the 63 tests that are under ./tests/unit/resources.  

out of the 63 tests that are under ./tests/unit/resources, 17 currently fail

The solution is to create an empty file called init.py to ./tests/unit/resources directory in order to allow the unittest discover routine to find the test cases

**Comment by svt-kmcdaniel** [comment]
The solution is to create an empty file called __init__.py to ./tests/unit/resources directory in order to allow the unittest discover routine to find the test cases

**Comment by svt-kmcdaniel** [comment]
The following pull request ( https://github.com/HewlettPackard/simplivity-python/pull/2 ) resolves the issue that is described here.

**Comment by sijeesh** [comment]
@svt-kmcdaniel , 
Thank you very much for finding this issue and fixing it.
We will be reviewing the PR and merging it soon.
